feat: add ci
Growthers/siphonica pull request #1
Opened 2023-01-11 08:56 UTC by Sigumaa

とりあえずのciを整備しました

PRでこんな感じに指摘してくれたりします(画像は例)

![image](https://user-images.githubusercontent.com/66453922/211761617-0139dd00-e8e1-41e9-a73a-1311cd84a6fe.png)
![image](https://user-images.githubusercontent.com/66453922/211761695-5aeaf977-7de5-48d4-b3e3-7aebadb67496.png)

2023-01-11 12:53 UTC, laminne requested changes

2023-01-11 12:53 UTC, laminne commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
改行...

2023-01-12 00:57 UTC, Sigumaa commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
@laminne 改行？

2023-01-12 04:08 UTC, m2en commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
@Sigumaa EoFのことだと思う
End of File

2023-01-12 04:09 UTC, m2en commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
要するにファイルの最後は改行してあげないといけない

2023-01-12 04:09 UTC, laminne commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
末尾改行警察だ！！！
@Sigumaa

2023-01-12 05:51 UTC, Sigumaa commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
o(*￣▽￣*)ブ

2023-01-12 07:39 UTC, re-taro commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
.editorconfigでも追加すればいいのに...

2023-01-12 08:35 UTC, m2en commented on .github/workflows/golangci.yml
> +          reporter: "github-pr-review"
それはそうね

2023-01-13 14:36 UTC, laminne approved these changes

2023-01-14 03:30 UTC, merged